#!/bin/bash
clear
echo -e "\033[1;33mOpciones de usuario:\033[1;30m
1) Desconectar un usuario
2) Eliminar un usuario
3) Eliminar y desconectar un usuario\033[0m"
read -p ": " option
 if [ $option -eq 1 ]; then
 read -p "Escriba el nombre de usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "El usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 echo "El usuario $name ha sido desconectado"
 exit
 fi
 
 if [ $option -eq 2 ]; then
 read -p "Escriba el nombre de usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "El usuario no existe"
 exit
 fi
 userdel --force $name > /dev/null 2>/dev/null
 echo "El usuario $name ha sido eliminado"
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Escriba el nombre de usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "El usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
 echo "El usuario $name ha sido desconectado y eliminado"
 exit
 fi
