#!/bin/bash
read -p "Escriba el nombre de usuario a editar: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "El usuario $namer no existe"
 exit
 fi
clear
echo -e "\033[1;33mQue desea modificar?\033[1;37m
1) Numero de logins
2) Fecha de expiracion
3) Cambiar contrasena de usuario"
read -p "Opcion: " option
if [ $option -eq 1 ]; then
read -p "Escriba el nuevo limite de logins: " liml
limite $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Escriba la nueva fecha de expiracion (AAAA/MM/DD): "
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Fecha de expiracion: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Escriba la nueva contrasena para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "Contrasena cambiada correctamente"
exit
fi
